import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen
      text-white`}>  
      <main className="p-4 max-w-2xl mx-auto">
      <header className="flex justify-between my-8">
      <Link href="/" className="flex gap-1">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="size-6">
  <path strokeLinecap="round" strokeLinejoin="round" d="M15.362 5.214A8.252 8.252 0 0 1 12 21 8.25 8.25 0 0 1 6.038 7.047 8.287 8.287 0 0 0 9 9.601a8.983 8.983 0 0 1 3.361-6.867 8.21 8.21 0 0 0 3 2.48Z" />
  <path strokeLinecap="round" strokeLinejoin="round" d="M12 18a3.75 3.75 0 0 0 .495-7.468 5.99 5.99 0 0 0-1.925 3.547 5.975 5.975 0 0 1-2.133-1.001A3.75 3.75 0 0 0 12 18Z" />
</svg>

        <span>EpicCaptions</span>
        </Link>
      <nav className="flex gap-6 text-white/70">
        <Link href="/">Home</Link>
        <Link href="/pricing">Pricing</Link>
        <a href="mailto:xyz@gmail.com">Contact</a>
      </nav>
    </header>
        {children}
      </main>
      </body>
    </html>
  );
}
